adding new concepts to valueset
PEDSnet/pedsnetcdm_to_pcornetcdm pull request #510
Opened 2020-11-17 17:20 UTC by ChavanShweta

OP-1126
OP-1100
Reference #508
@burrowse  Please review. Thanks.

2020-11-17 20:41 UTC, burrowse requested changes
Hey @ChavanShweta Thanks for working on this! See comments for the valuesets included in this PR.

2020-11-17 20:41 UTC, burrowse commented on v4.0_to_v6.0/sql_etl/data/concept_map.csv
> +Facility type,HOSPITAL_OUTPATIENT_NEUROSURGERY_CLINIC,HOSPITAL_OUTPATIENT_CLINIC-AMBULATORY_CARE-subset,8756,Outpatient Hospital Neurosurgery,38004459
HOSPITAL_OUTPATIENT_OBGYN_CLINIC was also added to the facility type valueset for v6 as well.

Add the following:

Facility type,HOSPITAL_OUTPATIENT_OBGYN_CLINIC,HOSPITAL_OUTPATIENT_CLINIC-AMBULATORY_CARE-subset,8756,Obstetrics and Gynecology,38004461

2020-11-17 20:41 UTC, burrowse commented on v4.0_to_v6.0/sql_etl/data/concept_map.csv
> +Facility type,HOSPITAL_OUTPATIENT_CARDIOLOGY_CLINIC,HOSPITAL_OUTPATIENT_CLINIC-AMBULATORY_CARE-subset,8756,Outpatient Hospital Cardiology,45756805
Add concept=38004451 mapping for cardiology as well.

2020-11-17 20:41 UTC, burrowse commented on v4.0_to_v6.0/sql_etl/data/concept_map.csv
> +vx_manufacturer_source,SOL,Solvay Pharmaceuticals,,,
Additional manufacturers need to be added:

vx_manufacturer_source,BN,Bavarian Nordic A/S,,,
vx_manufacturer_source,TVA,TEVA Pharmaceuticals USA,,,

2020-11-17 20:41 UTC, burrowse commented on v4.0_to_v6.0/sql_etl/data/concept_map.csv
> +result_qual_source,B POS,B Pos,,O positive,
Looks like a typo, is this supposed to say:

result_qual_source,O POS,O Pos,,O positive,

2020-11-17 20:41 UTC, burrowse commented on v4.0_to_v6.0/sql_etl/data/concept_map.csv
> +result_qual_source,SARS CORONAVIRUS 2,SARS coronavirus 2,,SARS coronavirus,
This should be updated to say SARS coronavirus 2 throughout we wouldn't want to mis-map 2 to 1

result_qual_source,SARS CORONAVIRUS 2,SARS coronavirus 2,,SARS coronavirus 2,

2020-11-17 21:07 UTC, burrowse commented
@ChavanShweta Please add these provider specialty maps... most codes are not in the vocabulary as yet but we should add them proactively since they are included in PCORnet's valueset.
[provider_specialty_maps.xlsx](https://github.com/PEDSnet/pedsnetcdm_to_pcornetcdm/files/5556228/provider_specialty_maps.xlsx)

2020-11-17 21:12 UTC, burrowse commented
@ChavanShweta Please add the following line for the language update to be proactive as well:

source_concept_class,target_concept, pcornet_name,source_concept_id,concept_description
Language,CNR,Montenegrin,,,

2020-11-17 22:06 UTC, burrowse commented
Work in progress for result unit mapping. Will add result unit source mapping asap.
[units_valueset_update.xlsx](https://github.com/PEDSnet/pedsnetcdm_to_pcornetcdm/files/5556487/units_valueset_update.xlsx)

2020-11-18 05:28 UTC, ChavanShweta commented on v4.0_to_v6.0/sql_etl/data/concept_map.csv
> +Facility type,HOSPITAL_OUTPATIENT_CARDIOLOGY_CLINIC,HOSPITAL_OUTPATIENT_CLINIC-AMBULATORY_CARE-subset,8756,Outpatient Hospital Cardiology,45756805
already present in mapping.

2020-11-18 14:37 UTC, burrowse commented on v4.0_to_v6.0/sql_etl/data/concept_map.csv
> +Facility type,HOSPITAL_OUTPATIENT_CARDIOLOGY_CLINIC,HOSPITAL_OUTPATIENT_CLINIC-AMBULATORY_CARE-subset,8756,Outpatient Hospital Cardiology,45756805
Can you point to a line? I didn't see it captured.

2020-11-18 14:49 UTC, burrowse commented on v4.0_to_v6.0/sql_etl/data/concept_map.csv
> +result_qual_source,O POS,B Pos,,O positive,
Still looks like this says B Pos in the third column...

2020-11-19 00:08 UTC, burrowse commented
@ChavanShweta Please see attached a result_unit_source valueset update.
[result_unit_source.xlsx](https://github.com/PEDSnet/pedsnetcdm_to_pcornetcdm/files/5563456/result_unit_source.xlsx)

2020-11-19 00:24 UTC, burrowse requested changes

2020-11-19 00:24 UTC, burrowse commented on v4.0_to_v6.0/sql_etl/data/concept_map.csv
> +Route,ENDOCERVICAL,Endocervical  route  (qualifier  value),45956872,cervical,
Add Route,EPILESIONAL,Epilesional route (qualifier value),35608078,Epilesional route
Add Route,EPILESIONAL,Epilesional route (qualifier value),45956880,Epilesional
Add  Route, INFILTRATION,Infiltration route (qualifier value),37397638,Infiltration route
Add  Route,INTESTINAL,Intestinal route (qualifier value),37207459,Intestinal route
Add  Route,INTRACERVICAL,Intracervical route (qualifier value),45956872,Intracervical
Add  Route,INTRACHOLANGIOPANCREATIC,Intracholangiopancreatic route (qualifier value),37207461,Intracholangiopancreatic route
Add  Route,INTRAPORTAL,Intraportal route (qualifier value),37207462,Intraportal route
Add  Route,OCULAR,Ocular route (qualifier value),4184451,Ocular
Add  Route,PERITUMORAL,Peritumoral route (qualifier value),37207463,Peritumoral route
Add  Route,POSTERIOR_JUXTASCLERAL,Posterior juxtascleral route (qualifier value),37207464,Posterior juxtascleral route
Add  Route,SUBRETINAL,Subretinal route (qualifier value),36703536,Subretinal route
Add  Route,SUBRETINAL,Subretinal route (qualifier value),37207465,Subretinal

2020-11-20 15:53 UTC, burrowse requested changes

2020-11-20 15:53 UTC, burrowse commented on v4.0_to_v6.0/sql_etl/data/concept_map.csv
> +Rx Dose Form,TOPICAL_SUSPENSION,TOPICAL_SUSPENSION=Topical Suspension,46234410,Topical Suspension,
Missing the following please add:

Rx Dose Form,POWDER_FOR_PYELOCALYCEAL_SOLUTION,POWDER_FOR_PYELOCALYCEAL_SOLUTION=Powder for Pyelocalyceal Solution,1146250,Powder for Pyelocalyceal Solution,
Rx Dose Form,MUCOUS_MEMBRANE_TOPICAL_SOLUTION,Mucous  Membrane  Topical  Solution,19082110,Mucous Membrane Topical Solution,
Rx Dose Form,CHEWABLE_EXTENDED_RELEASE_TABLET,Chewable Extended Release Tablet,37498346,Chewable Extended Release Oral Tablet,
Rx Dose Form,DELAYED_RELEASE_CAPSULE,Delayed Release Capsule,19082255,Delayed Release Oral Capsule,
Rx Dose Form,DELAYED_RELEASE_GRANULES,Delayed Release Granules,37499224,Delayed Release Oral Granules,
Rx Dose Form,DELAYED_RELEASE_TABLET,Delayed Release Tablet,19001949,Delayed Release Oral Tablet,
Rx Dose Form,EFFERVESCENT_TABLET,Effervescent Tablet,44817840,Effervescent Oral Tablet,
Rx Dose Form,GRANULES_FOR_ORAL_SOLUTION,Granules for Oral Solution,45775489,Granules for Oral Solution,
Rx Dose Form,GRANULES_FOR_ORAL_SUSPENSION,Granules for Oral Suspension,45775490,Granules for Oral Suspension,
Rx Dose Form,INHALANT_SPRAY,Inhalant Spray,37499223,Inhalation Spray,
Rx Dose Form,INHALANT_SUSPENSION,Inhalant Suspension,1356078,Inhalation Suspension,

2020-11-25 16:03 UTC, burrowse requested changes
See comments for changes needed

2020-11-30 15:25 UTC, burrowse requested changes

2020-11-30 15:25 UTC, burrowse commented on v4.0_to_v6.0/sql_etl/scripts/etl_scripts/h_condition.sql
> +'AC'  as condition_status,
AC is good here for condition_status.

Chief Compliant records should have 'CC' as condition_source though (line 108).

2020-11-30 15:33 UTC, ChavanShweta commented
@burrowse 
https://github.com/PEDSnet/pedsnetcdm_to_pcornetcdm/pull/510#discussion_r532679394
I have made the changes in the [condition_source](https://github.com/PEDSnet/pedsnetcdm_to_pcornetcdm/pull/510/commits/6a40489ba0106655867ecc162b58d334401ea681) for the chief complaints but the recent ETL documentation for pcornet doesn't say this valueset exists unless this is specific to COVID data.
[
![Screen Shot 2020-11-30 at 10 29 24 AM](https://user-images.githubusercontent.com/20832191/100629445-4b812d80-32f7-11eb-8804-163897bbae52.png)
](url)

2020-11-30 15:41 UTC, burrowse commented
> @burrowse
> [#510 (comment)](https://github.com/PEDSnet/pedsnetcdm_to_pcornetcdm/pull/510#discussion_r532679394)
> I have made the changes in the [condition_source](https://github.com/PEDSnet/pedsnetcdm_to_pcornetcdm/pull/510/commits/6a40489ba0106655867ecc162b58d334401ea681) for the chief complaints
> 
> https://github.com/PEDSnet/pedsnetcdm_to_pcornetcdm/blob/2293ca56e25b2c6578a660d640d80086b4fb7482/v4.0_to_v6.0/sql_etl/scripts/etl_scripts/h_condition.sql#L108
> 
> but the recent ETL documentation for pcornet doesn't say this valueset exists unless this is specific to COVID data.
> [ ![Screen Shot 2020-11-30 at 10 29 24 AM](https://user-images.githubusercontent.com/20832191/100629445-4b812d80-32f7-11eb-8804-163897bbae52.png)](url)

Thanks @ChavanShweta ! What version are you referencing? Looking at the v6 10/22 PDF CC is there. Did they make an update after?

![Screen Shot 2020-11-30 at 10 41 05 AM](https://user-images.githubusercontent.com/7452282/100630480-98b1cf00-32f8-11eb-91af-08012cbd14eb.png)

2020-12-01 20:08 UTC, burrowse requested changes

2020-12-01 20:08 UTC, burrowse commented on v4.0_to_v6.0/sql_etl/data/concept_map.csv
> +Rx Dose Form,MUCOUS_MEMBRANE_TOPICAL_SOLUTION,Mucus Membrane Topical Solution,19082110,Mucous Membrane Topical Solution,null
Update to say MUCUOUS_MEMBRANE_TOPICAL_SOLUTION

2020-12-04 20:12 UTC, burrowse approved these changes

2020-12-05 04:30 UTC, merged